CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS salondb;
CREATE DATABASE IF NOT EXISTS bookingdb;
CREATE DATABASE IF NOT EXISTS categorydb;
CREATE DATABASE IF NOT EXISTS notificationdb;
CREATE DATABASE IF NOT EXISTS paymentdb;
CREATE DATABASE IF NOT EXISTS reviewdb;
CREATE DATABASE IF NOT EXISTS `service-offeringdb`;
